export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const LOAD_CATEGORY_ALL_SUCCESS = 'LOAD_CATEGORY_ALL_SUCCESS';
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';

export const LOAD_CATEGORY_NEWS_ALL_SUCCESS = 'LOAD_CATEGORY_NEWS_ALL_SUCCESS';
export const LOAD_CATEGORY_NEWS_SUCCESS = 'LOAD_CATEGORY_NEWS_SUCCESS';
export const DELETE_CATEGORY_NEWS_SUCCESS = 'DELETE_CATEGORY_NEWS_SUCCESS';
export const GET_CATEGORY_NEWS_SUCCESS = 'GET_CATEGORY_NEWS_SUCCESS';

export const LOAD_SUPPLIER_ALL_SUCCESS = 'LOAD_SUPPLIER_ALL_SUCCESS';